const express = require('express');

const usaFieldHockey = require('./controllers/usaFieldHockey');
const perfectgameUrls = require('./controllers/perfectgame-urls');
const perfectgameScrape = require('./controllers/perfectgame-scrape');
const perfectgameScrapeExtraInfo = require('./controllers/perfectgame-scrape-extra');
const perfectgameScrapeOrg = require('./controllers/perfectgame-scrape-org');
const prepbaseballreportUrls = require('./controllers/prepbaseballreport-urls');
const prepbaseballreportUrlsAPI = require('./controllers/prepbaseballreport-urls-api');
const prepbaseballreportTeams = require('./controllers/prepbaseballreport-teams');
const prepbaseballreportSocial = require('./controllers/prepbaseballreport-social');
const washingtonyouthsoccer = require('./controllers/washingtonyouthsoccer');
const azsoccerassociation = require('./controllers/azsoccerassociation');
const calsouth = require('./controllers/calsouth');
const selectbaseballteamsUrls = require('./controllers/selectbaseballteams-urls');
const selectbaseballteamsUrlsRankings = require('./controllers/selectbaseballteams-urls-rankings');
const selectbaseballteamsUrlsTeams = require('./controllers/selectbaseballteams-urls-teams');
const selectbaseballteamsFinalData = require('./controllers/selectbaseballteams-final-data');
const ntxsoccer = require('./controllers/ntxsoccer-urls');
const perfectgameRankingsUrls = require('./controllers/perfectgame-rankings-urls');
const perfectgameRankingsOrg = require('./controllers/perfectgame-rankings-org');
const perfectgameRankingsFinal = require('./controllers/perfectgame-rankings-final');
const coloradosoccer = require('./controllers/coloradosoccer');
const nmysa = require('./controllers/nmysa');
const georgiasoccer = require('./controllers/georgiasoccer');
const exposureEventsUrls = require('./controllers/exposureevents-urls');
const exposureEventsFinal = require('./controllers/exposureevents-final');
const idahoyouthsoccer = require('./controllers/idahoyouthsoccer');
const southdakotasoccer = require('./controllers/southdakotasoccer');
const utahyouthsoccer = require('./controllers/utahyouthsoccer');
const montanayouthsoccer = require('./controllers/montanayouthsoccer');
const wyomingsoccer = require('./controllers/wyomingsoccer');
const hawaiisoccer = require('./controllers/hawaiisoccer');
const alaskayouthsoccer = require('./controllers/alaskayouthsoccer');
const nebraskastatesoccer = require('./controllers/nebraskastatesoccer');
const kansasyouthsoccer = require('./controllers/kansasyouthsoccer');
const stxsoccer = require('./controllers/stxsoccer');
const playlouisianasoccer = require('./controllers/playlouisianasoccer');
const alabamaSoccer = require('./controllers/alabamasoccer');
const marylandyouthsoccer = require('./controllers/marylandyouthsoccer');
const marylandyouthsoccerclubs = require('./controllers/marylandyouthsoccer-clubs');
const mnyouthsoccer = require('./controllers/mnyouthsoccer');
const arkansassoccer = require('./controllers/arkansassoccer');
const arkansassoccerclubs = require('./controllers/arkansassoccer-clubs');
const floridayouthsoccer = require('./controllers/floridayouthsoccer');
const floridayouthsoccerclubs = require('./controllers/floridayouthsoccer-clubs');
const iowasoccer = require('./controllers/iowasoccer');
const iowasoccerclubs = require('./controllers/iowasoccer-clubs');
const pawestsoccer = require('./controllers/pawestsoccer');
const pawestsoccerclubs = require('./controllers/pawestsoccer-clubs');
const mississippisoccer = require('./controllers/mississippisoccer');
const mississippisoccerclubs = require('./controllers/mississippisoccer-clubs');
const ncsoccer = require('./controllers/ncsoccer');
const ncsoccerclubs = require('./controllers/ncsoccer-clubs');
const nyswysa = require('./controllers/nyswysa');
const nevadayouthsoccer = require('./controllers/nevadayouthsoccer');
const tnsoccer = require('./controllers/tnsoccer');
const soccerri = require('./controllers/soccerri');
const soccermaine = require('./controllers/soccermaine');
const scyouthsoccer = require('./controllers/scyouthsoccer');
const ohiosoccer = require('./controllers/ohiosoccer');
const calnorth = require('./controllers/calnorth');
const soccerindiana = require('./controllers/soccerindiana');
const missourisoccer = require('./controllers/missourisoccer');
const wiyouthsoccer = require('./controllers/wiyouthsoccer-urls');
const wiyouthsoccerdata = require('./controllers/wiyouthsoccer-data');
const ecnlboys = require('./controllers/ecnlboys');
const girlsacademyleague = require('./controllers/girlsacademyleague');
const mlssoccer = require('./controllers/mlssoccer');
const usysnationalleague = require('./controllers/usysnationalleague');
const kysoccer = require('./controllers/kysoccer');

const router = express.Router();

router.get('/usafieldhockey', usaFieldHockey.usaFieldHockey);
router.get('/perfectgame-urls', perfectgameUrls.perfectgameUrls);
router.get('/perfectgame-scrape', perfectgameScrape.perfectgameScrape);
router.get('/perfectgame-scrape-extra', perfectgameScrapeExtraInfo.perfectgameScrapeExtraInfo);
router.get('/perfectgame-scrape-org', perfectgameScrapeOrg.perfectgameScrapeOrg);
router.get('/prepbaseballreport-urls', prepbaseballreportUrls.prepbaseballreportUrls);
router.get('/prepbaseballreport-urls-api', prepbaseballreportUrlsAPI.prepbaseballreportUrlsAPI);
router.get('/prepbaseballreport-teams', prepbaseballreportTeams.prepbaseballreportTeams);
router.get('/prepbaseballreport-social', prepbaseballreportSocial.prepbaseballreportSocial);
router.get('/washingtonyouthsoccer', washingtonyouthsoccer.washingtonyouthsoccer);
router.get('/azsoccerassociation', azsoccerassociation.azsoccerassociation);
router.get('/calsouth', calsouth.calsouth);
router.get('/selectbaseballteams-urls', selectbaseballteamsUrls.selectbaseballteamsUrls);
router.get('/selectbaseballteams-urls-rankings', selectbaseballteamsUrlsRankings.selectbaseballteamsUrlsRankings);
router.get('/selectbaseballteams-urls-teams', selectbaseballteamsUrlsTeams.selectbaseballteamsUrlsTeams);
router.get('/selectbaseballteams-final-data', selectbaseballteamsFinalData.selectbaseballteamsFinalData);
router.get('/ntxsoccer-urls', ntxsoccer.ntxsoccer);
router.get('/perfectgame-rankings-urls', perfectgameRankingsUrls.perfectgameRankingsUrls);
router.get('/perfectgame-rankings-org', perfectgameRankingsOrg.perfectgameRankingsOrg);
router.get('/perfectgame-rankings-final', perfectgameRankingsFinal.perfectgameRankingsFinal);
router.get('/coloradosoccer', coloradosoccer.coloradosoccer);
router.get('/nmysa', nmysa.nmysa);
router.get('/georgiasoccer', georgiasoccer.georgiasoccer);
router.get('/exposureevents-urls', exposureEventsUrls.exposureEventsUrls);
router.get('/exposureevents-final', exposureEventsFinal.exposureEventsFinal);
router.get('/idahoyouthsoccer', idahoyouthsoccer.idahoyouthsoccer);
router.get('/southdakotasoccer', southdakotasoccer.southdakotasoccer);
router.get('/utahyouthsoccer', utahyouthsoccer.utahyouthsoccer);
router.get('/montanayouthsoccer', montanayouthsoccer.montanayouthsoccer);
router.get('/wyomingsoccer', wyomingsoccer.wyomingsoccer);
router.get('/hawaiisoccer', hawaiisoccer.hawaiisoccer);
router.get('/alaskayouthsoccer', alaskayouthsoccer.alaskayouthsoccer);
router.get('/nebraskastatesoccer', nebraskastatesoccer.nebraskastatesoccer);
router.get('/kansasyouthsoccer', kansasyouthsoccer.kansasyouthsoccer);
router.get('/stxsoccer', stxsoccer.stxsoccer);
router.get('/playlouisianasoccer', playlouisianasoccer.playlouisianasoccer);
router.get('/alabamasoccer', alabamaSoccer.alabamaSoccer);
router.get('/marylandyouthsoccer', marylandyouthsoccer.marylandyouthsoccer);
router.get('/marylandyouthsoccer-clubs', marylandyouthsoccerclubs.marylandyouthsoccerclubs);
router.get('/mnyouthsoccer', mnyouthsoccer.mnyouthsoccer);
router.get('/arkansassoccer', arkansassoccer.arkansassoccer);
router.get('/arkansassoccer-clubs', arkansassoccerclubs.arkansassoccer);
router.get('/floridayouthsoccer', floridayouthsoccer.floridayouthsoccer);
router.get('/floridayouthsoccer-clubs', floridayouthsoccerclubs.floridayouthsoccer);
router.get('/iowasoccer', iowasoccer.iowasoccer);
router.get('/iowasoccer-clubs', iowasoccerclubs.iowasoccer);
router.get('/pawestsoccer', pawestsoccer.pawestsoccer);
router.get('/pawestsoccer-clubs', pawestsoccerclubs.pawestsoccer);
router.get('/mississippisoccer', mississippisoccer.mississippisoccer);
router.get('/mississippisoccer-clubs', mississippisoccerclubs.mississippisoccer);
router.get('/ncsoccer', ncsoccer.ncsoccer);
router.get('/ncsoccer-clubs', ncsoccerclubs.ncsoccer);
router.get('/nyswysa', nyswysa.nyswysa);
router.get('/nevadayouthsoccer', nevadayouthsoccer.nevadayouthsoccer);
router.get('/tnsoccer', tnsoccer.tnsoccer);
router.get('/soccerri', soccerri.soccerri);
router.get('/soccermaine', soccermaine.soccermaine);
router.get('/scyouthsoccer', scyouthsoccer.scyouthsoccer);
router.get('/ohiosoccer', ohiosoccer.ohiosoccer);
router.get('/calnorth', calnorth.calnorth);
router.get('/soccerindiana', soccerindiana.soccerindiana);
router.get('/missourisoccer', missourisoccer.missourisoccer);
router.get('/wiyouthsoccer-urls', wiyouthsoccer.wiyouthsoccer);
router.get('/wiyouthsoccer-data', wiyouthsoccerdata.wiyouthsoccer);
router.get('/ecnlboys', ecnlboys.ecnlboys);
router.get('/girlsacademyleague', girlsacademyleague.girlsacademyleague);
router.get('/mlssoccer', mlssoccer.mlssoccer);
router.get('/usysnationalleague', usysnationalleague.usysnationalleague);
router.get('/kysoccer', kysoccer.kysoccer);

module.exports = router;
